#!/bin/bash
set -e

# Create local user matching the AD principal name
if ! id -u testuser >/dev/null 2>&1; then
  useradd -m -s /bin/bash testuser
  echo "testuser:Password123!" | chpasswd
fi


# Update /etc/hosts
if ! grep -q "linux-server.lab.local" /etc/hosts; then
cat << 'EOF' >> /etc/hosts
192.168.56.10 ad-server.lab.local ad-server
192.168.56.11 linux-server.lab.local linux-server
192.168.56.12 linux-client.lab.local linux-client
EOF
fi
sed -i 's/127.0.2.1 linux-server linux-server/127.0.2.1 linux-server.lab.local linux-server/g' /etc/hosts

# Install Kerberos clients and SSH Server non-interactively
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y krb5-user libpam-krb5 libpam-ccreds openssh-server

# Copy Kerberos config
cp /vagrant/krb5.conf /etc/krb5.conf

# Import the host keytab generated by the AD Controller
echo "Waiting for keytab file /vagrant/linux-server.keytab..."
while [ ! -f /vagrant/linux-server.keytab ]; do
  sleep 5
done

cp /vagrant/linux-server.keytab /etc/krb5.keytab
chmod 600 /etc/krb5.keytab
chown root:root /etc/krb5.keytab

# Configure SSHD to support GSSAPI authentication
sed -i 's/#GSSAPIAuthentication no/GSSAPIAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/GSSAPIAuthentication no/GSSAPIAuthentication yes/g' /etc/ssh/sshd_config
if ! grep -q "GSSAPIAuthentication yes" /etc/ssh/sshd_config; then
  echo "GSSAPIAuthentication yes" >> /etc/ssh/sshd_config
fi

if ! grep -q "GSSAPICleanupCredentials yes" /etc/ssh/sshd_config; then
  echo "GSSAPICleanupCredentials yes" >> /etc/ssh/sshd_config
fi

systemctl restart sshd

echo "Linux Server provisioned successfully."
